const dataArray = [
    {
      employeeName: "Harsha Johny",
      employeeId: "E001",
      joiningDate: "12.4.3",
      role: "Software Engineer",
      status: "Inactive",
      experience: "5 years",
      address: "123 ABC Street, City, Country",  
    },
    {
      employeeName: "Sara John",
      employeeId: "E002",
      joiningDate: "22.3.10",
      role: "UI",
      status: "Active",
      experience: "3 years",
      address: "456 XYZ Avenue, Town, Country",  
    },
    {
      employeeName: "Ravi Sreenivash",
      employeeId: "E003",
      joiningDate: "21.6.5",
      role: "Marketing Manager",
      status: "Probation",
      experience: "2 years",
      address: "789 Main Road, Village, Country",  
    },
    {
      employeeName: "Neha Chandran",
      employeeId: "E004",
      joiningDate: "20.12.20",
      role: "fullstack",
      status: "Active",
      experience: "4 years",
      address: "321 PQR Boulevard, Suburb, Country",  
    },
 
      {
        employeeName: "Harsha Johny",
        employeeId: "E001",
        joiningDate: "12.4.3",
        role: "Software Engineer",
        status: "Inactive",
        experience: "5 years",
        address: "123 ABC Street, City, Country",
      },
      {
        employeeName: "Sara John",
        employeeId: "E002",
        joiningDate: "22.3.10",
        role: "UI",
        status: "Active",
        experience: "3 years",
        address: "456 XYZ Avenue, Town, Country",
      },
      {
        employeeName: "Ravi Sreenivash",
        employeeId: "E003",
        joiningDate: "21.6.5",
        role: "Marketing Manager",
        status: "Probation",
        experience: "2 years",
        address: "789 Main Road, Village, Country",
      },
      {
        employeeName: "Neha Chandran",
        employeeId: "E004",
        joiningDate: "20.12.20",
        role: "fullstack",
        status: "Active",
        experience: "4 years",
        address: "321 PQR Boulevard, Suburb, Country",
      },
      {
        employeeName: "John Doe",
        employeeId: "E005",
        joiningDate: "2020-05-15",
        role: "Software Engineer",
        status: "Probation",
        experience: "4 years",
        address: "567 Oak Street, City, Country",
      },
      {
        employeeName: "Jane Smith",
        employeeId: "E006",
        joiningDate: "2019-10-20",
        role: "Marketing Manager",
        status: "Active",
        experience: "5 years",
        address: "890 Pine Road, Town, Country",
      },
      {
        employeeName: "Michael Johnson",
        employeeId: "E007",
        joiningDate: "2021-02-10",
        role: "Data Analyst",
        status: "Inactive",
        experience: "3 years",
        address: "432 Maple Avenue, City, Country",
      },
      {
        employeeName: "Sarah Brown",
        employeeId: "E008",
        joiningDate: "2018-07-01",
        role: "HR Coordinator",
        status: "Active",
        experience: "7 years",
        address: "654 Cedar Lane, Suburb, Country",
      },
      {
        employeeName: "Kevin Lee",
        employeeId: "E009",
        joiningDate: "2020-11-30",
        role: "Financial Analyst",
        status: "Active",
        experience: "2 years",
        address: "876 Elm Street, City, Country",
      },
      {
        employeeName: "Emily Wilson",
        employeeId: "E010",
        joiningDate: "2017-09-05",
        role: "Senior Software Developer",
        status: "Active",
        experience: "10 years",
        address: "543 Birch Road, Town, Country",
      },
      {
        employeeName: "David Garcia",
        employeeId: "E011",
        joiningDate: "2019-03-18",
        role: "Product Manager",
        status: "Active",
        experience: "6 years",
        address: "987 Walnut Drive, City, Country",
      },
      {
        employeeName: "Lisa Anderson",
        employeeId: "E012",
        joiningDate: "2022-01-15",
        role: "UI Designer",
        status: "Probation",
        experience: "1 year",
        address: "210 Cedar Lane, Suburb, Country",
      },
      {
        employeeName: "Alex Johnson",
        employeeId: "E013",
        joiningDate: "2019-08-20",
        role: "Software Engineer",
        status: "Active",
        experience: "4 years",
        address: "876 Oak Street, City, Country",
      },
      {
        employeeName: "Sophia Davis",
        employeeId: "E014",
        joiningDate: "2020-04-12",
        role: "Marketing Specialist",
        status: "Active",
        experience: "3 years",
        address: "543 Pine Road, Town, Country",
      },
      {
        employeeName: "Daniel Brown",
        employeeId: "E015",
        joiningDate: "2018-11-25",
        role: "Financial Analyst",
        status: "Inactive",
        experience: "6 years",
        address: "987 Maple Avenue, City, Country",
      },
      {
        employeeName: "Olivia Miller",
        employeeId: "E016",
        joiningDate: "2017-12-30",
        role: "HR Manager",
        status: "Active",
        experience: "8 years",
        address: "654 Elm Street, City, Country",
      },
    
 
  ];
  
  export default dataArray;
  
  // Add more employees with addresses
 
